# Generated by Django 4.2.7 on 2023-11-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_rename_content_id_notification_object_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
        migrations.AddField(
            model_name="notification",
            name="is_showed",
            field=models.BooleanField(default=False),
        ),
    ]
