# Generated by Django 4.0.2 on 2023-12-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_is_read_notification_is_showed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
