# Generated by Django 4.2.7 on 2023-11-15 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                (
                    "degree_of_importance",
                    models.CharField(
                        choices=[
                            ("1", "Not Important"),
                            ("2", "Slightly Important"),
                            ("3", "Moderately Important"),
                            ("4", "Important"),
                            ("5", "Very Important"),
                        ],
                        max_length=1,  # Add max_length parameter
                    ),
                ),
                (
                    "rate",
                    models.CharField(
                        choices=[
                            ("1", "Poor"),
                            ("2", "Fair"),
                            ("3", "Good"),
                            ("4", "Very Good"),
                            ("5", "Perfect"),
                        ],
                        max_length=1,  # Add max_length parameter
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_date", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="ticket.discussion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
