# Generated by Django 4.2.7 on 2024-01-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='discussion',
            name='department',
            field=models.CharField(choices=[('S', 'Support Department'), ('T', 'Tech Departemnt'), ('F', 'Fiance Department'), ('H', 'Human Resource Department'), ('C', 'Central Department')], default='S', max_length=1),
        ),
    ]
