# Generated by Django 4.2.7 on 2023-11-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="is_terminated",
            field=models.BooleanField(default=False),
        ),
    ]
