# Generated by Django 4.2.7 on 2023-11-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_discussion_is_terminated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discussion",
            options={"ordering": ("-start_time",)},
        ),
        migrations.AddField(
            model_name="discussion",
            name="is_answered",
            field=models.BooleanField(default=False),
        ),
    ]
