# Generated by Django 4.0.2 on 2023-12-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='degree_of_importance',
            field=models.CharField(choices=[('1', 'Not Important'), ('2', 'Slightly Important'), ('3', 'Moderately Important'), ('4', 'Important'), ('5', 'Very Important')], max_length=1),
        ),
    ]
